# Generated by Django 5.2 on 2026-05-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='theater',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
