# Generated by Django 5.2 on 2026-05-01 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='theater',
            new_name='theator',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='theater',
            new_name='theator',
        ),
        migrations.AlterField(
            model_name='theator',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theators', to='movies.movies'),
        ),
    ]
