# Generated by Django 5.2 on 2026-06-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_theater_booking_theator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller')], default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Korean', 'Korean')], default='Action', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='movies',
            index=models.Index(fields=['name'], name='movies_movi_name_ed0ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='movies',
            index=models.Index(fields=['genre'], name='movies_movi_genre_6c937d_idx'),
        ),
        migrations.AddIndex(
            model_name='movies',
            index=models.Index(fields=['language'], name='movies_movi_languag_67fd1d_idx'),
        ),
    ]
