# Generated by Django 5.2 on 2026-06-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_genre_movies_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.URLField(),
        ),
    ]
